# Generated by Django 4.0.1 on 2022-01-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('contacto', models.IntegerField()),
            ],
        ),
    ]
